server:
  port: 8081
spring:
  profiles:
    active: @activatedProperties@
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
