server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/practice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
